import { defineConfig } from 'cspell'

export default defineConfig({
  version: '0.2',

  ignorePaths: [
    '**/.git',
    '**/.turbo/**',
    '**/pnpm-lock.yaml',
    '**/eslint.config.js',
    '**/.gitignore',
    '**/.prettierignore',
    '**/commitlint.config.js',
    '**/package.json',
    '**/*.mp4',
    '**/*.png',
    '**/*.jpg',
    '**/*.svg',
    '**/*.ico',
    '**/node_modules/**',
    '**/dist/**',
    '**/build/**',
    '**/lib/**',
    '**/docs/**',
    '**/vendor/**',
    '**/public/**',
    '**/static/**',
    '**/out/**',
    '**/tmp/**',
    '**/*.d.ts',
    '**/*.md',
    '**/stats.html',
  ],
  dictionaries: [
    'typescript',
    'node',
    'html',
    'css',
    'bash',
    'misc',
    'npm',
    'fonts',
    'filetypes',
    'softwareTerms',
  ],
  words: [
    'turborepo',
    'pnpm',
    'vite',
    'rolldown',
    'tsdown',
    'cspell',
    'unplugin',
    'axios',
    'pinia',
    'vitest',
    'monorepo',
    'tsconfck',
    'jiti',
    'rimraf',
    'lucide',
    'vuejs',
    'vue-tsc',
    'unocss',
    'vueuse',
  ],
})
